nombre=input("ingrese su nombre ").title()
apellido=input("ingrese su apellido  ").upper()
cargo=input("imgrese su cargo en la empresa  ").title()
correo=input("ingrese su correo ").lower()
ID=input(" ingrese su cedula ")
edad=input("edad ")
print("--------")
print(f"{apellido}, {nombre}")
print(f"{cargo}, {edad}")


print(correo)
print()
print(ID+"-"+ str (len(ID)))
print("--------------")
